PLAYFIELD_SIZE = 16
MAX_TICEMEM = 16

# Directions
D_UP = 1
D_RIGHT = 2
D_DOWN = 3
D_LEFT = 4

D_INVERT = {
    D_UP: D_DOWN,
    D_RIGHT: D_LEFT,
    D_DOWN: D_UP,
    D_LEFT: D_RIGHT,
}

# Keys
K_SHOOT = 32
K_LEFT = 37
K_UP = 38
K_RIGHT = 39
K_DOWN = 40

K_UNDO = 117
K_QUIT = 256
K_QUIT = 256

# Terrain
GRASS = 0
FLAG = 2
WATER = 3
CONVEYOR_UP = 15
CONVEYOR_RIGHT = 16
CONVEYOR_DOWN = 17
CONVEYOR_LEFT = 18
ICE = 24
THINICE = 25

BRIDGE = 26  # Custom

TUNNEL_0_RED = 64
TUNNEL_1_GREEN = 66
TUNNEL_2_BLUE = 68
TUNNEL_3_CYAN = 70
TUNNEL_4_YELLOW = 72
TUNNEL_5_PINK = 74
TUNNEL_6_WHITE = 76
TUNNEL_7_GREY = 78

TUNNEL_0_RED_WAITING = 65
TUNNEL_1_GREEN_WAITING = 67
TUNNEL_2_BLUE_WAITING = 69
TUNNEL_3_CYAN_WAITING = 71
TUNNEL_4_YELLOW_WAITING = 73
TUNNEL_5_PINK_WAITING = 75
TUNNEL_6_WHITE_WAITING = 77
TUNNEL_7_GREY_WAITING = 79

TUNNEL_ALL = [
    TUNNEL_0_RED,
    TUNNEL_1_GREEN,
    TUNNEL_2_BLUE,
    TUNNEL_3_CYAN,
    TUNNEL_4_YELLOW,
    TUNNEL_5_PINK,
    TUNNEL_6_WHITE,
    TUNNEL_7_GREY,
    TUNNEL_0_RED_WAITING,
    TUNNEL_1_GREEN_WAITING,
    TUNNEL_2_BLUE_WAITING,
    TUNNEL_3_CYAN_WAITING,
    TUNNEL_4_YELLOW_WAITING,
    TUNNEL_5_PINK_WAITING,
    TUNNEL_6_WHITE_WAITING,
    TUNNEL_7_GREY_WAITING,
]

# Items
TANK = TANK_UP = 1
TANK_RIGHT = 33
TANK_DOWN = 34
TANK_LEFT = 35

SOLID = 4
BLOCK = 5
WALL = 6

EMPTY = 36

ANTITANK_UP = 7
ANTITANK_RIGHT = 8
ANTITANK_DOWN = 9
ANTITANK_LEFT = 10

ANTITANKS_ALL = [
    ANTITANK_UP,
    ANTITANK_RIGHT,
    ANTITANK_DOWN,
    ANTITANK_LEFT,
]

MIRROR_LEFT_UP = 11
MIRROR_UP_RIGHT = 12
MIRROR_RIGHT_DOWN = 13
MIRROR_DOWN_LEFT = 14

DEADANTITANK_UP = 27
DEADANTITANK_RIGHT = 28
DEADANTITANK_DOWN = 29
DEADANTITANK_LEFT = 30

GLASS = 19

ROTMIRROR_LEFT_UP = 20
ROTMIRROR_UP_RIGHT = 21
ROTMIRROR_RIGHT_DOWN = 22
ROTMIRROR_DOWN_LEFT = 23

DEADANTITANK_ALL = [
    DEADANTITANK_UP,
    DEADANTITANK_RIGHT,
    DEADANTITANK_DOWN,
    DEADANTITANK_LEFT,
]

MIRROR_ALL = [
    MIRROR_LEFT_UP,
    MIRROR_UP_RIGHT,
    MIRROR_RIGHT_DOWN,
    MIRROR_DOWN_LEFT,
    ROTMIRROR_LEFT_UP,
    ROTMIRROR_UP_RIGHT,
    ROTMIRROR_RIGHT_DOWN,
    ROTMIRROR_DOWN_LEFT,
]

# LT_Sound_Types
S_Bricks = 1
S_Fire = 2
S_Move = 3
S_Head = 4
S_Turn = 5
S_EndLev = 6
S_Die = 7
S_Anti1 = 8
S_Anti2 = 9
S_Deflb = 10
S_LaserHit = 11
S_Push2 = 12
S_Push1 = 13
S_Rotate = 14
S_Push3 = 15
S_Sink = 16

TunnelID = {
    TUNNEL_0_RED: 0,
    TUNNEL_1_GREEN: 1,
    TUNNEL_2_BLUE: 2,
    TUNNEL_3_CYAN: 3,
    TUNNEL_4_YELLOW: 4,
    TUNNEL_5_PINK: 5,
    TUNNEL_6_WHITE: 6,
    TUNNEL_7_GREY: 7,
    TUNNEL_0_RED_WAITING: 0,
    TUNNEL_1_GREEN_WAITING: 1,
    TUNNEL_2_BLUE_WAITING: 2,
    TUNNEL_3_CYAN_WAITING: 3,
    TUNNEL_4_YELLOW_WAITING: 4,
    TUNNEL_5_PINK_WAITING: 5,
    TUNNEL_6_WHITE_WAITING: 6,
    TUNNEL_7_GREY_WAITING: 7,
}

Tunnel_from_ID = {
    0: TUNNEL_0_RED,
    1: TUNNEL_1_GREEN,
    2: TUNNEL_2_BLUE,
    3: TUNNEL_3_CYAN,
    4: TUNNEL_4_YELLOW,
    5: TUNNEL_5_PINK,
    6: TUNNEL_6_WHITE,
    7: TUNNEL_7_GREY,
}

Tunnel_Set_Not_Waiting = {
    TUNNEL_0_RED: TUNNEL_0_RED,
    TUNNEL_1_GREEN: TUNNEL_1_GREEN,
    TUNNEL_2_BLUE: TUNNEL_2_BLUE,
    TUNNEL_3_CYAN: TUNNEL_3_CYAN,
    TUNNEL_4_YELLOW: TUNNEL_4_YELLOW,
    TUNNEL_5_PINK: TUNNEL_5_PINK,
    TUNNEL_6_WHITE: TUNNEL_6_WHITE,
    TUNNEL_7_GREY: TUNNEL_7_GREY,
    TUNNEL_0_RED_WAITING: TUNNEL_0_RED,
    TUNNEL_1_GREEN_WAITING: TUNNEL_1_GREEN,
    TUNNEL_2_BLUE_WAITING: TUNNEL_2_BLUE,
    TUNNEL_3_CYAN_WAITING: TUNNEL_3_CYAN,
    TUNNEL_4_YELLOW_WAITING: TUNNEL_4_YELLOW,
    TUNNEL_5_PINK_WAITING: TUNNEL_5_PINK,
    TUNNEL_6_WHITE_WAITING: TUNNEL_6_WHITE,
    TUNNEL_7_GREY_WAITING: TUNNEL_7_GREY,
}

Tunnel_Set_Waiting = {
    TUNNEL_0_RED: TUNNEL_0_RED_WAITING,
    TUNNEL_1_GREEN: TUNNEL_1_GREEN_WAITING,
    TUNNEL_2_BLUE: TUNNEL_2_BLUE_WAITING,
    TUNNEL_3_CYAN: TUNNEL_3_CYAN_WAITING,
    TUNNEL_4_YELLOW: TUNNEL_4_YELLOW_WAITING,
    TUNNEL_5_PINK: TUNNEL_5_PINK_WAITING,
    TUNNEL_6_WHITE: TUNNEL_6_WHITE_WAITING,
    TUNNEL_7_GREY: TUNNEL_7_GREY_WAITING,
    TUNNEL_0_RED_WAITING: TUNNEL_0_RED_WAITING,
    TUNNEL_1_GREEN_WAITING: TUNNEL_1_GREEN_WAITING,
    TUNNEL_2_BLUE_WAITING: TUNNEL_2_BLUE_WAITING,
    TUNNEL_3_CYAN_WAITING: TUNNEL_3_CYAN_WAITING,
    TUNNEL_4_YELLOW_WAITING: TUNNEL_4_YELLOW_WAITING,
    TUNNEL_5_PINK_WAITING: TUNNEL_5_PINK_WAITING,
    TUNNEL_6_WHITE_WAITING: TUNNEL_6_WHITE_WAITING,
    TUNNEL_7_GREY_WAITING: TUNNEL_7_GREY_WAITING,
}

DECODE_TABLE = {
    0: (GRASS, EMPTY),
    1: (GRASS, TANK),
    2: (FLAG, EMPTY),
    3: (WATER, EMPTY),
    4: (GRASS, SOLID),
    5: (GRASS, BLOCK),
    6: (GRASS, WALL),
    7: (GRASS, ANTITANK_UP),
    8: (GRASS, ANTITANK_RIGHT),
    9: (GRASS, ANTITANK_DOWN),
    10: (GRASS, ANTITANK_LEFT),
    11: (GRASS, MIRROR_LEFT_UP),
    12: (GRASS, MIRROR_UP_RIGHT),
    13: (GRASS, MIRROR_RIGHT_DOWN),
    14: (GRASS, MIRROR_DOWN_LEFT),
    15: (CONVEYOR_UP, EMPTY),
    16: (CONVEYOR_RIGHT, EMPTY),
    17: (CONVEYOR_DOWN, EMPTY),
    18: (CONVEYOR_LEFT, EMPTY),
    19: (GRASS, GLASS),
    20: (GRASS, ROTMIRROR_LEFT_UP),
    21: (GRASS, ROTMIRROR_UP_RIGHT),
    22: (GRASS, ROTMIRROR_RIGHT_DOWN),
    23: (GRASS, ROTMIRROR_DOWN_LEFT),
    24: (ICE, EMPTY),
    25: (THINICE, EMPTY),
    64: (TUNNEL_0_RED, EMPTY),
    66: (TUNNEL_1_GREEN, EMPTY),
    68: (TUNNEL_2_BLUE, EMPTY),
    70: (TUNNEL_3_CYAN, EMPTY),
    72: (TUNNEL_4_YELLOW, EMPTY),
    74: (TUNNEL_5_PINK, EMPTY),
    76: (TUNNEL_6_WHITE, EMPTY),
    78: (TUNNEL_7_GREY, EMPTY),
}

SPRITE_MAPPING = {
    GRASS: 1,
    TANK_UP: 2,
    TANK_RIGHT: 3,
    TANK_DOWN: 4,
    TANK_LEFT: 5,
    FLAG: (6, 7, 8),
    WATER: (9, 10, 11),
    DEADANTITANK_DOWN: 12,
    SOLID: 13,
    BLOCK: 14,
    WALL: 15,
    ANTITANK_UP: (16, 17, 18),
    BRIDGE: 19,
    MIRROR_LEFT_UP: 20,
    MIRROR_UP_RIGHT: 21,
    MIRROR_RIGHT_DOWN: 22,
    MIRROR_DOWN_LEFT: 23,
    CONVEYOR_UP: (24, 25, 26),
    CONVEYOR_RIGHT: (27, 28, 29),
    CONVEYOR_DOWN: (30, 31, 32),
    CONVEYOR_LEFT: (33, 34, 35),
    ANTITANK_RIGHT: (36, 37, 38),
    ANTITANK_DOWN: (39, 40, 41),
    ANTITANK_LEFT: (42, 43, 44),
    GLASS: 45,
    # GLASS_GREEN: 46,
    ROTMIRROR_LEFT_UP: 47,
    ROTMIRROR_UP_RIGHT: 48,
    ROTMIRROR_RIGHT_DOWN: 49,
    ROTMIRROR_DOWN_LEFT: 50,
    # GLASS_RED: 51,
    DEADANTITANK_RIGHT: 52,
    DEADANTITANK_LEFT: 53,
    DEADANTITANK_UP: 54,
    # TUNNEL: 55
    ICE: 56,
    THINICE: 57,
}

GetTankDirectional = {
    D_UP: TANK_UP,
    D_RIGHT: TANK_RIGHT,
    D_DOWN: TANK_DOWN,
    D_LEFT: TANK_LEFT,
}

BMP_TUNNEL_MASK = 55
BMP_GLASS_RED = 51
BMP_GLASS_GREEN = 46

DIFFICULTY_TEXTS = {
    1: "Kids",
    2: "Easy",
    4: "Medium",
    8: "Hard",
    16: "Deadly",
}

LaserColorR = "RED"
LaserColorG = "GREEN"
